# Generated by Django 2.1 on 2018-08-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('posto', models.CharField(max_length=40, verbose_name='Posto')),
                ('tipo_combustivel', models.CharField(default='GASOLINA', max_length=10, verbose_name='Tipo do combustível')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('km_percorridos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Km percorridos')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
