# Generated by Django 2.1 on 2018-08-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='km_media_por_litro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Km percorridos'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='tipo_combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('GNV', 'GNV'), ('DIESEL', 'Diesel')], default='GASOLINA', max_length=10, verbose_name='Tipo do combustível'),
        ),
    ]
